language: ruby
bundler_args: --without production
addons:
   code_climate:
     repo_token: 62c9b3dcf62121f24010397d203442ce2151a158d94b9cc2602b1a2b7cdd9410
rvm:
  - 2.2.6
  - 2.3.2
branches:
  only:
    - master
script: bundle exec rspec spec
